CREATE TABLE topicos (
    id BIGINT NOT NULL AUTO_INCREMENT,
    titulo VARCHAR(255) NOT NULL,
    mensagem TEXT NOT NULL,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50) NOT NULL DEFAULT 'ABERTO',
    autor VARCHAR(100) NOT NULL,
    curso VARCHAR(100) NOT NULL,
    
    PRIMARY KEY (id)
); 